mendersoftware/inventory

.travis.yml
=> Fix travis codecov integration

datastore_mongo.go, datastore_mongo_test.go
also, selectively set created_ts.
Issues: MEN-649
@maciejmrowiec @kjaskiewiczz @bboozzoo @marekswiecznik
=> datastore_mongo: set updated_ts on UpsertAttributes

api_inventory.go, api_inventory_test.go, docs/devices_api.yml, docs/integrations_api.yml
Issues: MEN-501
* Fixing issue with duplicated http_code. Origin: https://github.com/mendersoftware/deviceauth/pull/64#pullrequestreview-3878165
* added request_id field to error response body.
@mchalski @maciejmrowiec
=> Unify API error output 

README.md, config/config.go, config/config_test.go, main.go
Issues: MEN-702
@kjaskiewiczz  @maciejmrowiec
=> Exposing service configuration through environment

datastore_mongo.go, datastore_mongo_test.go
Issues: MEN-731
Added "$and" operator to query.
@GregorioDiStefano @mchalski
=> datastore_mongo: fix devices search by multiple attributes

Dockerfile, datastore_mongo_test.go
Issues: MEN-886
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
=> Dockerfile: migrate to alpine:3.4

docs/management_api.yml
Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>
=> Follow API change in the gateway.

api_inventory.go, api_inventory_test.go, utils/http.go, utils/http_test.go
Issues: MEN-881
https://tools.ietf.org/html/rfc3986#section-5.4
@mendersoftware/rndity @maciejmrowiec
=> relative urls in Location and Link headers

docs/management_api.yml
=> docs: include user auth info in mgmt api

LIC_FILES_CHKSUM.sha256, docs/devices_api.yml, docs/management_api.yml, middleware.go, vendor/github.com/mendersoftware/go-lib-micro/customheader/middleware.go, vendor/vendor.json
Change public routing to v1, v2, v3 schema (v1).
Update documentation.
Remove port 8080 from swagger.
Add service version header returned by API
@mendersoftware/rndity
=> MEN-963: Update API versioning.

.travis.yml, docs/management_api.yml
Issues: MEN-984
@mendersoftware/rndity @maciejmrowiec 
EDIT - stacking the npm fix too
=> docs: DELETE /devices/:id spec

api_inventory.go, api_inventory_test.go, datastore.go, datastore_mongo.go, datastore_mongo_test.go, inventory.go, inventory_test.go, mock_data_store_test.go, mock_inventory_app_test.go
Issues: MEN-986
@mendersoftware/rndity @maciejmrowiec
=> Remove device

.travis.yml, tests/run.sh
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
=> ignore testing packages when calculating code coverage

main.go, store/mongo/datastore_mongo.go, tests/run.sh
Deprecates #82 
@mendersoftware/rndity @maciejmrowiec
=> mongo safe mode

.travis.yml
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
=> travis: fix pushing of container

.travis.yml
Minor cleanups to travis file organization.
=> Build docker image on compile_and_basic_tests and use it for dockerhub.

api/http/api_inventory.go, api/http/api_inventory_test.go, docs/management_api.yml
Issues: MEN-1379
Signed-off-by: Piotr Przybylak <piotr.przybylak@rndity.com>
=> restrict special chars in group names (PUT /devices/:id/groups)

.travis.yml, main.go, store/mongo/datastore_mongo.go, tests/Dockerfile, tests/common.py, tests/tests/client.py, tests/tests/test_cli.py, tests/tests/test_creating_devices.py, tests/tests/test_groupping_devices.py, tests/tests/test_inventory_searching.py, tests/tests/test_inventory_sorting.py, tests/tests/test_remove_device_groupping.py
=> 'migrate [--tenant=<id>]' command

main.go
=> Start server on no-subcommand. Fix regression. 

.travis.yml
=> travis: remove deprecated --email flag on docker login

.travis.yml
=> Update mongo setup in travis.

store/mongo/datastore_mongo_test.go, vendor/github.com/mendersoftware/mendertesting/check_license_go_code.sh, vendor/vendor.json
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
=> Update mendertesting dependency and affected copyright years.

.travis.yml, api/http/api_inventory.go, api/http/api_inventory_test.go, store/datastore.go, store/mongo/datastore_mongo.go
=> FIx licence dates on editer files (test fails)

api/http/api_inventory.go, api/http/api_inventory_test.go, inv/inventory_test.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go, store/query.go, tests/tests/test_cli.py
regex filtering was an experimental feature and will not be present in the inventory service anymore
Issues: https://tracker.mender.io/browse/MEN-2473
=> remove regex filtering

.travis.yml, api/http/api_inventory.go, api/http/api_inventory_test.go, model/device.go, model/device_test.go, store/mongo/datastore_mongo.go, tests/common.py, tests/conftest.py, tests/inventory_items, tests/run.sh, tests/tests/test_api_internal.py, tests/tests/test_inventory_searching.py, tests/tests/test_inventory_sorting.py
Issues: https://tracker.mender.io/browse/MEN-2474
=> Extend device attribute with a scope.

.gitlab-ci.yml
This is a dummy pipeline where to base on the rest of the work. I need to get this one in master to keep developing/experimenting with my GitLab integration.
=> Add initial GitLab Pipeline file

api/http/api_inventory.go, api/http/api_inventory_test.go, inv/inventory.go, inv/inventory_test.go, inv/mocks/InventoryApp.go, model/device.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Issues: https://tracker.mender.io/browse/MEN-2474
=> introduce internal endpoint for patching attributes (PATCH /api/internal/v2/inventory/devices/:id)

inv/inventory_test.go, main.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go, store/mongo/init_dbtest_test.go, store/mongo/migration_0_2_0.go, store/mongo/migration_0_2_0_test.go, tests/tests/test_cli.py
https://tracker.mender.io/browse/MEN-2476
=> inventory attributes migration

api/http/api_inventory.go, api/http/api_inventory_test.go, model/device.go
Issue https://tracker.mender.io/browse/MEN-2478
=> api/http: V1 endpoints return devices with "inventory" attributes only

api/http/api_inventory.go
https://tracker.mender.io/browse/MEN-2475
=> fix PATCH internal/v2/devices

.gitlab-ci.yml
Same as for the rest of the repos
=> Set expiration for artifacts in Pipeline to 2w

docs/management_api_v2.yml
=> MEN-3099: v2 search end-point spec

store/mongo/datastore_mongo.go
=> do not return nil in groups

api/http/api_inventory.go, api/http/api_inventory_test.go, inv/inventory.go, inv/inventory_test.go, inv/mocks/InventoryApp.go, model/filters.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Backport the filter execution end-points, both management and internal,
from the enterprise version of inventory.
=> Filter execution end-points (management and internal)

docs/management_api.yml, docs/management_api_v2.yml
=> Clarify description of the 'per_page` parameter in API calls

.github/stale.yml
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
=> add(stalebot): Add a configuration file for stalebot

.dependabot/config.yml
=> Feature/dependabot 

api/http/api_inventory.go, api/http/api_inventory_test.go
=> MEN-3637 internal endpoint to set arbitrary attributes.

model/device.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> Refactor GetDevices to avoid using the aggregation pipeline

docs/devices_api.yml, docs/management_api.yml, docs/management_api_v2.yml
=> API spec fixes: schema and hostname - 2.0.x

api/http/api_inventory.go
=> MEN-3793 remove device on reject

api/http/api_inventory.go, api/http/api_inventory_test.go
https://tracker.mender.io/browse/MEN-3846
needed for:
https://github.com/mendersoftware/deviceauth/pull/378
https://github.com/mendersoftware/integration/pull/978
Pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/671855381
(only 'open' tests will pass - we'll need an automerge to `-enterprise` as well)
=> allow updates to 'noauth' state

.gitlab-ci.yml
=> Upgrade golang version in unit tests to 1.14

api/http/api_inventory.go, api/http/api_inventory_test.go, docs/devices_api.yml, inv/inventory.go, inv/inventory_test.go, inv/mocks/InventoryApp.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> MEN-4001: new device API end-point to replace inventory attributes

tests/Dockerfile
=> Acceptance tests fail with INTERNALERROR 

api/http/api_inventory.go, api/http/api_inventory_test.go, tests/Dockerfile
MEN-4029 Deploy to group for os onprem fix.
ChangeLog:none
(cherry picked from commit 458c78b27f85acba96692576bb8925bfd8f875fe)
(cherry picked from commit d1bfc5fa93c55bd35caa856f866a49e92ecc690c)
=> MEN-4029 Deploy to group for os onprem fix.

api/http/api_inventory.go, api/http/api_inventory_test.go, docs/management_api_v2.yml, inv/inventory.go, inv/inventory_test.go, inv/mocks/InventoryApp.go, model/attribute.go, model/filters.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> MEN-3510: new API end-point to return the list of filterable attributes

api/http/api_inventory.go, api/http/api_inventory_test.go, docs/internal_api.yml, inv/inventory.go, inv/mocks/InventoryApp.go, model/device.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Issues: https://tracker.mender.io/browse/MEN-4112
=> new device status update flow

store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go, store/mongo/migration_1_0_1.go, store/mongo/migration_1_0_1_test.go, store/mongo/migrations.go
=> Index commonly used inventory attributes' values

store/mongo/datastore_mongo.go
=> Set device's updated_ts on insert, as UI displays it for pending devices

tests/tests/client.py
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
=> use traefik's X-Forwarded-* headers

tests/tests/client.py
https://tracker.mender.io/browse/MEN-4327
=> merge feature-traefik

docs/management_api_v2.yml, model/filters.go, model/filters_test.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Changelog: Support returning a subset of attributes in filters/search
=> Update filters/search endpoint to return a subset of attributes

api/http/api_inventory.go, api/http/api_inventory_test.go, docs/internal_api.yml, store/datastore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> Fix: internal EP to update device's status returns 409 on write conflict

tests/Dockerfile, tests/common.py, tests/docker-compose-acceptance.yml, tests/tests/client.py, tests/tests/test_api_internal.py, tests/tests/test_cli.py
https://tracker.mender.io/browse/QA-260
=> common acceptance test image

docs/internal_api_v2.yml
=> MEN-4670: fix host and scheme in internal API docs

store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> MEN-4723: FIX: allow sorting by device ID

client/devicemonitor/client.go
=> Fix internal UI to gather devicemonitor data

api/http/api_inventory.go, api/http/api_inventory_test.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go, store/query.go
=> MEN-4644: add support for filtering datetimes (e.g. `updated_ts`)

client/workflows/client.go, client/workflows/client_test.go, client/workflows/mocks/Client.go, inv/inventory.go, inv/inventory_test.go
=> MEN-4843: start reindex workflows using the batch API end-point

.gitlab-ci.yml, api/http/api_inventory.go, client/workflows/client.go, inv/inventory.go, main.go, server.go, store/datastore.go, store/mongo/datastore_mongo.go, store/mongo/migration_0_2_0.go, store/mongo/migration_1_0_0.go, store/mongo/migrations.go, utils/http.go
=> QA-235: pipeline: Switch to static checks by golangci-lint

docs/internal_api_v2.yml, docs/management_api_v2.yml, inv/inventory.go, inv/inventory_test.go, model/device.go, model/filters.go, model/requests.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go, store/mongo/migration_1_1_0.go, store/mongo/migration_1_1_0_test.go, store/mongo/migrations.go, utils/search.go, utils/search_test.go
=> feat: enhance the filtering API to support device full-text search

store/mongo/datastore_mongo.go, utils/search.go
=> fix: device search reindexing

Dockerfile, Dockerfile.acceptance-testing
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
=> chore: moved docker images away from root

api/http/api_inventory.go, client/devicemonitor/client.go
Changelog: Title
Ticket: MEN-5713
=> fix: replace colon with hash for path params modifiers in URLs

store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Changelog: Title
Ticket: MEN-6705
=> fix: update `updated_ts` only if we are updating the inventory scope

inv/inventory.go, inv/inventory_test.go
=> fix: proper comparation of attributes if they are slices

.gitlab-ci.yml
=> Fix production rolling release

store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Changelog: Title
Ticket: MEN-6764
=> fix: sort devices by name

model/device.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Ticket: [MEN-6878](https://northerntech.atlassian.net/browse/MEN-6878)
[MEN-6878]: https://northerntech.atlassian.net/browse/MEN-6878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: do not set updated_ts field when inserting the device

api/http/api_inventory.go
=> fix: store "check_in_time" attribute as ISODate instead of string

api/http/api_inventory.go
=> fix: attribute modification in the range loop
