mendersoftware/inventory

docs/devices_api.yml, docs/integrations_api.yml
Issues: MEN-655
Changelog (besides style/layout)
- reduced the search/sort mini-language description - we implement just a minimal subset
- moved lots of stuff from global description to param/struct descriptions
Possible quirks:
- can't see a way to properly document search, except in the description (search params are free-form, attr names are not known a priori
- attribute value is still an 'object' - I couldn't find any way to document multi-type fields properly
This spec is a lot bigger, with lots of examples, so please take a good look.
@michaelatmender @maciejmrowiec
=> docs: update api specs according to guildelines

docs/devices_api.yml
Gateway configuration maps /api/devices/0.1/inventory/device/attributes
to /api/0.1.0/attributes.
See: https://github.com/mendersoftware/mender-api-gateway-docker/blob/master/nginx.conf#L86
@maciejmrowiec @mchalski @kjaskiewiczz @marekswiecznik
=> docs/devices: use correct device attributes endpoint

docs/devices_api.yml, docs/integrations_api.yml
helpful for tests - swagger python client doesn't handle 'object' well
@GregorioDiStefano @maciejmrowiec
=> docs: change attribute 'value' field type to 'string'

api_inventory.go, api_inventory_test.go, docs/management_api.yml
Do not return 404 if DELETE on /devices/{id} did not find any resources to
delete. In the end, the effect of DELETE if there was no device and if one was
removed is exactly the same (device is no longer present), but non-success
status may confuse some integration tools.
@maciejmrowiec @mendersoftware/rndity
=> api: http: do replace 404 with 204 on DELETE if device was not found.

.travis.yml, Dockerfile.acceptance-testing
The binary built for acceptance tests is named `inventory` just like the main
'release' binary. This may cause confusion when testing manually. The patch
renames accepantce tests binary to `inventory-test` and updates both travis
script file and acceptance tests Dockerfile.
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
=> travis/acceptance: use a different name for acceptance tests binary

tests/tests/test_groupping_devices.py
When creating a large number of groups within a short period of time will cause
heavy logging. This may in turn cause docker shim to get stuck pushing the logs
from the container outside. A workaround is to either manually `cat` on the
stdout file descriptor of docker shim or reduce logging.
@mendersoftware/rndity @GregorioDiStefano
=> tests: create fewer groups in acceptance tests

store/mongo/datastore_mongo_test.go
https://tracker.mender.io/browse/MEN-1766
tests relying on exact mongo error messages started failing with a patch
update of the mongo 3.4 package in trusty/multiverse; the messages are
different now, and in general shouldn't be relied on.
refactor to avoid always comparing against an exact error - IsError signals
that an error occured, and OutputError will be set optionally, if
we mean to do an exact comparison.
changelog: none
=> store/mongo: refactor failing tests

api/http/api_inventory.go, api/http/api_inventory_test.go
We couldn't filter attributes with ":" correctly.
For mac address "ff:ff:ff:ff:ff:ff" example, we will request with the query string like this: `attr_name1=ff:ff:ff:ff:ff:ff`, but actually the filter will be "ff" not "ff:ff:ff:ff:ff:ff".
=> Allow filter with ":"

.travis.yml, LICENSE, LIC_FILES_CHKSUM.sha256, api/http/api_inventory.go, api/http/api_inventory_test.go, docs/management_api.yml, inv/inventory.go, inv/inventory_test.go, inv/mocks/InventoryApp.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
the additional cost per request is most likely set off by the removed requirement for multiple requests to get all the devices per group, that are currently fired every time another group is selected in the ui...
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
=> get total device count on dev-list request to allow leaner pagination in gui

api/http/api_inventory_test.go, model/device.go
this catches a blank string too, and we want to allow those.
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
https://tracker.mender.io/browse/MEN-2435
tested in https://github.com/mendersoftware/integration/pull/587
=> api/http: relax 'required' on attribute value

api/http/api_inventory.go, api/http/api_inventory_test.go, api/http/dto.go, api/http/dto_test.go, docs/management_api_v2.yml, model/device.go, tests/tests/test_inventory_searching.py, tests/tests/test_inventory_sorting.py
https://tracker.mender.io/browse/MEN-2523
the first 2 commits are a bugfix of the recent v1 modification, at least i'm 99% sure it's what it should look like @kjaskiewiczz.
also, the last commit is a fix to the modified `PATCH v1/devices` (fixed scope assignments).
also, to discuss:
- I created `management_api_v2.yml`, with just the `GET v2/devices` endpoint - will later be moved to just `management_api.yml` (we can't do it just yet - v1 EPs were not rerouted yet to v2) - is that correct?
it seems like this to me, e.g. acceptance tests need functioning v1 still...
- we're introducing a separate Device resource (with grouped attributes) for GET v2. should we also migrate `GET v2/devices/:id` to this new representation? or leave it as is. we might need an extra followup task
there's an …
=> GET /devices v2

tests/docker-compose-integration.yml, tests/docker-compose.yml
Update docker-compose version to 2.1 for acceptance tests to comply with the rest of the integration compose files.
Also, remove docker-compose-integration.yml
=> Update docker-compose version to 2.1 for acceptance tests

tests/common.py
reason:
pymongo.errors.OperationFailure: Direct writes against
config.transactions cannot be performed using a transaction or on a
session.
introduced in 3.6 apparently - sessions are used by default, and
'config' is untouchable on a session.
https://jira.mongodb.org/browse/SERVER-35244
=> tests/common: mongo cleanup: don't cleanup 'config' db

main.go
The migrate command, when used without the `--tenant` option, migrates
the database of all the tenants. This behaviour is consistent with the
`--automigrate` option of the `server` command.
If the `--tenant` option is specified, the migration runs only for the
provided tenant ID.
=> Update migrate command to be consistent with server --automigrate

.gitignore, api/http/api_inventory.go, api/http/api_inventory_test.go, model/device.go
Internal endpoint to set a status of given devices
--
* **deviceauth** calls _update_device_status_ [[1](https://github.com/mendersoftware/workflows/pull/40)] workflow to propagate information on device status to inventory.
* **inventory** exposes internal API to set status for a list of devices [[2](https://github.com/mendersoftware/inventory-enterprise/pull/24)].
* _/filters/search_ can be use by UI to get list of devices as a single place of information.
* a new scope `identity` [4](https://github.com/mendersoftware/integration/pull/881)
related PRs:
* [1] https://github.com/mendersoftware/workflows/pull/40
* [2] https://github.com/mendersoftware/inventory-enterprise/pull/24
* [3] https://github.com/mendersoftware/deviceauth/pull/324
* [4] …
=> internal endpoint to set the attributes in scope for a device

model/device.go
Only affects the API-facing `updated_ts` attribute for fetching devices.
=> FIX: Incorrect unmarshalling datetime from device document

model/device.go, store/mongo/datastore_mongo.go
As fieldnames containing dots gets transformed to embedded documents, we
must disallow such fields from making it to the DB. This PR replaces
such field names using the following replacements:
- `'.'` -> `'_'`
- `'$'` -> `'_S_'`
=> FIX: Replace fieldnames containing '.' and '$'

api/http/api_inventory.go
Deviceauth synces all statuses to inventory service.
In case of device being dismissed from the preauthorized devices list
(user did not accept the device) there is no status to sync, so:
* update device status with _decommissioned_ status is called
* inventory service deletes device when it receives the update
see: deviceauth/28926e747f9c9ac06dafe3eca679b796f5e1e5b6
https://github.com/mendersoftware/deviceauth/pull/355
=> Delete device upon receiving _decommission_ status update.

docs/devices_api.yml, docs/management_api.yml, docs/management_api_v2.yml
* [API spec] Consistently use host hosted.mender.io across all repos
=> API spec fixes: schema and hostname

api/http/api_inventory.go, api/http/api_inventory_test.go, docs/management_api.yml, inv/inventory.go, inv/inventory_test.go, inv/mocks/InventoryApp.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Added an optional `status` parameter to `GET /groups` to be able to filter out devices used for evaluating groups to the given status.
I made the storage and app interfaces generic in the expectation that there might come a need for `/search` like interface in the future.
Goes along with mendersoftware/gui#926.
=> MEN-3906: Add status query parameter to GET /groups

model/device.go, model/device_test.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
We need to replace dots and dollars in the key used to store inventory
attributes to allow mongodb successfully store and query them without
unnecessary nesting.
=> MEN-3478: replace dot/dollar in inventory keys with unicode equivalents

api/http/api_inventory.go, api/http/api_inventory_test.go, inv/inventory.go, inv/inventory_test.go, inv/mocks/InventoryApp.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
The deviceauth service consumes the internal management API end-points
to update the inventory fields. In this case, we don't want to update
the update_ts timestamp. We provide a new method in the DataStore
(UpsertDevicesAttributesWithUpdated) which explicitly updates the
update_ts field, and we use this method from the device API end-points
consumed by the Mender Client to update the device inventory data.
=> Do not update the updated_ts timestamp in internal end-points

docs/management_api.yml
The endpoint should never been exposed.
Using the endpoint leads to data inconsistency in the system.
=> docs: deprecate DELETE /devices/{id} management endpoint

api/http/api_inventory.go, api/http/api_inventory_test.go, docs/internal_api.yml, docs/management_api.yml, tests/tests/client.py
Introduce a new internal end-point to delete (decommission) a device
from the inventory microservice. The new end-point replaces an
equivalent one in the management APIs we deprecated because there was no
reason for users to manually trigger the decommissioning for a device.
At the same time, update the implementation of the old management
endpoint (DELETE) with a new semantic: reset the device's inventory
data, removing all the attributes in the inventory scope. This is what
the end-point was reallly about in its original intentions.
=> MEN-4525: improve device decommissioning and inventory data reset

docs/management_api.yml
=> docs: add the scope property to the attribute definition in the api docs v1

api/http/api_inventory.go, api/http/api_inventory_test.go
Ticket: MEN-6477
In the /filters/attributes endpoint, in case there are no attributes,
return empty list instead of null.
=> fix value returned by /filters/attributes endpoint

Dockerfile, Dockerfile.acceptance-testing
This makes the caller traces in logs and errors system-independent.
=> chore(docker): Add -trimpath to go build command
